# Generated by Django 4.1.5 on 2023-01-05 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborators', '0002_collaborator_departments_collaborator_enterprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
