# Generated by Django 4.1.5 on 2023-01-05 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_collaborator_departments_collaborator_enterprise_and_more'),
        ('overtime_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='collaborators.collaborators'),
            preserve_default=False,
        ),
    ]
