# Generated by Django 4.1.5 on 2023-01-05 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='departments',
            field=models.ManyToManyField(to='departments.department'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='enterprises.enterprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
